# Makefile.Unix
TOP = ../..
include $(TOP)/config/CONFIG_APP
#-----------------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

SCRIPTS += SetPerms

include $(TOP)/config/RULES.Host
#-----------------------------------------------
#  ADD RULES AFTER THIS LINE
