# Makefile.Vx
TOP = ../..
include $(TOP)/config/CONFIG_APP
#-----------------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

USR_CFLAGS += -D$(T_A)

ifdef WITH_MCAN
USR_CFLAGS += -DMCAN_ON
endif

PROD += initHooks.o
PROD += mv162InitHooks.o

include $(TOP)/config/RULES.Vx
#-----------------------------------------------
#  ADD RULES AFTER THIS LINE
