# Makefile.Vx
TOP = ../..
include $(TOP)/config/CONFIG_APP
#-----------------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#USR_CFLAGS += -D$(T_A)

include $(TOP)/config/RULES.Vx
#-----------------------------------------------
#  ADD RULES AFTER THIS LINE
