#!/bin/sh
#
# Sets file permissions in an EPICS / CapFast / CVS directory tree
#
# Time-stamp: <97/12/03 11:37:23 lange>
# $Id: SetPerms,v 1.9 1997/12/03 10:38:13 lange Exp $
#
PROG=`basename $0`

USAGE="usage: $PROG [directory ...]"

if [ $# = 0 ]; then
    dirs=`pwd`
else
    for f
    do
	if [ ! -d $f ]; then
	    echo $f is not a directory.
	    echo $USAGE
	    exit 1
	else
	    case $f in                   # Prefix relative paths with `pwd`
	    /*) ;;
	    *) f=`pwd`/$f ;;
	    esac
	    dirs="$dirs $f"
	fi
    done
fi

# Exit if not in .../base or .../extensions or .../csr/capfast (I *love* shell programming)

for f in $dirs
do
    case $f in
    *CVS/epics* | *CVS/epics/base* | */CVS/epics/extensions* | */CVS/epics/templates* | */CVS/IOC* | */CVS/OPI* | */CVS/RulesFiles* )

# Set everything to group epics and ???r-X---

	echo EPICS repository: $f
	echo Setting everything to group epics and mode ???r-X--- ...
		       
	chgrp -R epics $f/* > /dev/null 2>&1
	chmod -R g=rX,o= $f/* > /dev/null 2>&1

# Set all directories to mode rwxrwxr-x

	echo Setting all directories to mode rwxrwxr-x ...

	find $f/ -type d -user $USER | xargs chmod u=rwx,g=rwx,o=rx

	;;

    *CVS/mCAN*)

# Set everything to group interf and ???r-X---

	echo MultiCAN repository: $f
	echo Setting everything to group interf and mode ???r-X--- ...

	chgrp -R interf $f/* > /dev/null 2>&1
	chmod -R g=rX,o= $f/* > /dev/null 2>&1

# Set all directories to mode rwxrwxr-x

	echo Setting all directories to mode rwxrwxr-x ...

	find $f/ -type d -user $USER | xargs chmod u=rwx,g=rwx,o=rx 

	;;

    */epics/base* | */epics/extensions* | */epics/local*)

# Set everything to group epics and ???r-X---

	echo EPICS tree: $f
	echo Setting everything to group epics and mode ???r-X--- ...
		       
	chgrp -R epics $f/* > /dev/null 2>&1
	chmod -R g=rX,o= $f/* > /dev/null 2>&1
		       
# Set all directories and executables to group epima and mode rwxrwxr-x

	echo Setting all directories and executables to group epima and mode rwxrwxr-x ...

	files=`find $f/ -user $USER -and \( -type d -or -type f -perm +111 \)`
	if [ -n "$files" ]; then
	    echo $files | xargs chmod u=rwx,g=rwx,o=rx
	    echo $files | xargs chgrp epima
	fi
       
# Make config files world readable

	if [ -d $f/config ]; then
	  echo Making config, dbd, include and lib files world readable ...
		       
	  chmod -R o+r $f/config $f/dbd $f/include $f/lib $f/lib_sl > /dev/null 2>&1
	fi

# Make binary executables unreadable for others

	echo Making binary executables unreadable for others...
		       
	find $f/ -type f -perm +111 -user $USER \
	 -exec /bin/sh -c "chmod g-w {}; file {} | grep -q executable && chmod o-r {}" \;

	;;
  
    */csr/capfast*)

# Set everything to group epics and ???r-Xr-X

	echo CapFast tree: $f
	echo Setting everything to group epics and mode ???r-Xr-X ...
		       
	chgrp -R epics $f/* > /dev/null 2>&1
	chmod -R go=rX $f/* > /dev/null 2>&1
		       
# Set all directories and executables to group epima and mode rwxrwxr-x

	echo Setting all directories and executables to group epima and mode rwxrwxr-x ...

	files=`find $f/ -user $USER -and \( -type d -or -type f -perm +111 \)`
	if [ -n "$files" ]; then
	    echo $files | xargs chmod u=rwx,g=rwx,o=rx
	    echo $files | xargs chgrp epima
	fi
       
# Make binary executables unreadable for others

	echo Making binary executables unreadable for others...
		       
	find $f/ -type f -perm +111 -user $USER \
	 -exec /bin/sh -c "chmod g-w {}; file {} | grep -q executable && chmod o-r {}" \;

	;;
  
  */epics/templates*)

# Set everything to group epics and ???r-Xr-X

	echo EPICS templates tree: $f
	echo Setting everything to group epics and mode ???r-Xr-X ...
		       
	chgrp -R epics $f/* > /dev/null 2>&1
	chmod -R g=rX,o=rX $f/* > /dev/null 2>&1
		       
# Set all directories and executables to group epima and mode rwxrwxr-x

	echo Setting all directories and executables to group epima and mode rwxrwxr-x ...
		       
	files=`find $f/ -user $USER -and \( -type d -or -type f -perm +111 \)`
	if [ -n "$files" ]; then
	    echo $files | xargs chmod u=rwx,g=rwx,o=rx
	    echo $files | xargs chgrp epima
	fi
	;;
  
  */epics/config*)
	   
	echo Setting everything to group epics and mode ???r-X--- ...
			
	chgrp epics $f/* > /dev/null 2>&1
	chmod g=rX,o= $f/* > /dev/null 2>&1

	;;

  *)
	echo Not in EPICS or CapFast Tree.
	exit 1
	;;
    esac
done

exit 0
