#!/bin/sh
#
# Sets file permissions in an EPICS / CapFast / CVS directory tree
#
# Completely cron-job-aware, runs even with "PATH=/usr/bin"
#
# Time-stamp: <99/02/02 18:37:49 lange>
# $Id: SetPerms,v 1.18 1999/02/02 17:40:07 lange Exp $
#
PROG=`basename $0`

USAGE="usage: $PROG [directory ...]"

USER=`whoami`

if [ $# = 0 ]; then
    dirs=`pwd`
else
    for f
    do
	if [ ! -d $f ]; then
	    echo $f is not a directory.
	    echo $USAGE
	    exit 1
	else
	    case $f in                   # Prefix relative paths with `pwd`
	    /*) ;;
	    *) f=`pwd`/$f ;;
	    esac
	    dirs="$dirs $f"
	fi
    done
fi

for f in $dirs
do
    case $f in

###############################################################################

    *CVS/epics* | *CVS/epics/base* | */CVS/epics/extensions* | */CVS/epics/templates* | */CVS/IOC* | */CVS/OPI* | */CVS/RulesFiles* )

# Set everything to group epics and ???r-X---

	echo EPICS repository: $f
	echo Setting everything to group epics and mode ???r-X--- ...
		       
	chgrp -R epics $f/* > /dev/null 2>&1
	chmod -R g=rX,o= $f/* > /dev/null 2>&1

# Set all directories to mode rwxrwxr-x

	echo Setting all directories to mode rwxrwxr-x ...

	find $f/ -type d -user $USER | xargs chmod u=rwx,g=rwx,o=rx 2>/dev/null

# Set all fileattr g+w

	find $f/ -user $USER -name fileattr | xargs chmod g+w 2>/dev/null

	;;

###############################################################################

    *CVS/mCAN*)

# Set everything to group interf and ???r-X---

	echo MultiCAN repository: $f
	echo Setting everything to group interf and mode ???r-X--- ...

	chgrp -R interf $f/* > /dev/null 2>&1
	chmod -R g=rX,o= $f/* > /dev/null 2>&1

# Set all directories to mode rwxrwxr-x

	echo Setting all directories to mode rwxrwxr-x ...

	find $f/ -type d -user $USER | xargs chmod u=rwx,g=rwx,o=rx  2>/dev/null

# Set all fileattr g+w

	find $f/ -user $USER -name fileattr | xargs chmod g+w 2>/dev/null

	;;

###############################################################################

    *CVS/medmPanels/*)

# Set everything to group swdevel and ???r-X---

	echo medmPanels repository: $f
	echo Setting everything to group swdevel and mode ???r-X--- ...

	chgrp -R swdevel $f/* > /dev/null 2>&1
	chmod -R g=rX,o= $f/* > /dev/null 2>&1

# Set all directories to mode rwxrwxr-x

	echo Setting all directories to mode rwxrwxr-x ...

	find $f/ -type d -user $USER | xargs chmod u=rwx,g=rwx,o=rx  2>/dev/null

# Set all fileattr g+w

	find $f/ -user $USER -name fileattr | xargs chmod g+w 2>/dev/null

	;;

###############################################################################

    */vw/* | */epics/base* | */epics/extensions* )

# Set everything to group epics and ???r-X---

	echo EPICS/vxWorks  tree: $f
	echo Setting everything to group epics and mode ???r-X--- ...
		       
	chgrp -R epics $f/* > /dev/null 2>&1
	chmod -R g=rX,o= $f/* > /dev/null 2>&1
		       
# Set all directories and executables to group epima and mode rwxrwxr-x

	echo Setting all directories and executables to group epima and mode rwxrwxr-x ...

	files=`find $f/ -user $USER -a \( -type d -o -type f -perm +111 \)`
	if [ -n "$files" ]; then
	    echo $files | xargs chmod u=rwx,g=rwx,o=rx
	    echo $files | xargs chgrp epima
	fi
       
# Make config files etc. world readable

	files=`find . -type d | grep "/config\|/dbd\|/include\|/lib\|/lib_sl\|/templates" | grep -v "/src/"`
	if [ -n "$files" ]; then
	  echo Making config, dbd, include and lib files world readable ...
          echo $files | xargs chmod -R o+r $f > /dev/null 2>&1
	fi

# Make binary executables unreadable for others

	echo Making binary executables unreadable for others...
		       
	find $f/ -type f -perm +111 -user $USER \
	 -exec /bin/sh -c "chmod g-w {}; file {} | grep -q executable && chmod o-r {}" \;

	;;
  
###############################################################################

    */csr/capfast*)

# Set everything to group epics and ???r-Xr-X

	echo CapFast tree: $f
	echo Setting everything to group epics and mode ???r-Xr-X ...
		       
	chgrp -R epics $f/* > /dev/null 2>&1
	chmod -R go=rX $f/* > /dev/null 2>&1
		       
# Set all directories and executables to group epima and mode rwxrwxr-x

	echo Setting all directories and executables to group epima and mode rwxrwxr-x ...

	files=`find $f/ -user $USER -a \( -type d -o -type f -perm +111 \)`
	if [ -n "$files" ]; then
	    echo $files | xargs chmod u=rwx,g=rwx,o=rx
	    echo $files | xargs chgrp epima
	fi
       
# Make binary executables unreadable for others

	echo Making binary executables unreadable for others...
		       
	find $f/ -type f -perm +111 -user $USER \
	 -exec /bin/sh -c "chmod g-w {}; file {} | grep -q executable && chmod o-r {}" \;

	;;
  
###############################################################################

  */epics/templates*)

# Set everything to group epics and ???r-Xr-X

	echo EPICS templates tree: $f
	echo Setting everything to group epics and mode ???r-Xr-X ...
		       
	chgrp -R epics $f/* > /dev/null 2>&1
	chmod -R g=rX,o=rX $f/* > /dev/null 2>&1
		       
# Set all directories and executables to group epima and mode rwxrwxr-x

	echo Setting all directories and executables to group epima and mode rwxrwxr-x ...
		       
	files=`find $f/ -user $USER -a \( -type d -o -type f -perm +111 \)`
	if [ -n "$files" ]; then
	    echo $files | xargs chmod u=rwx,g=rwx,o=rx
	    echo $files | xargs chgrp epima
	fi
	;;
  
###############################################################################

  */epics/config*)
	   
	echo Setting everything to group epics and mode ???r-X--- ...
			
	chgrp epics $f/* > /dev/null 2>&1
	chmod g=rX,o= $f/* > /dev/null 2>&1

	;;

###############################################################################

    */htdocs*)

# Set everything to group wwwadm and ???r-Xr-X

	echo Web tree: $f
	echo Setting everything to group wwwadm and mode ???r-Xr-X ...
		       
	chgrp -R wwwadm $f/* > /dev/null 2>&1
	chmod -R go=rX $f/* > /dev/null 2>&1

# Set all directories to mode rwxrwxr-x

	echo Setting all directories to mode rwxrwxr-x ...

	find $f/ -type d -user $USER | xargs chmod u=rwx,g=rwx,o=rx 2>/dev/null

	;;

###############################################################################

  *)
	echo Not in EPICS or CapFast or Web Tree.
	exit 1
	;;
    esac
done

exit 0
