# Makefile.Vx
TOP = ../..
include $(TOP)/config/CONFIG_APP
#-----------------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

INC += debugmsg.h

PROD += initHooks.o

include $(TOP)/config/RULES.Vx
#-----------------------------------------------
#  ADD RULES AFTER THIS LINE
