# Makefile.Vx
TOP = ../..
include $(TOP)/config/CONFIG_APP
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

APPNAME = csm

SRCS.c += csmbase.c
PROD += csmbase.o
INC += csmbase.h

#Note that the command line that builds the
#library $(LIBNAME) may be HUGE (>3kB)
#
include $(TOP)/config/RULES.Vx
#----------------------------------------
#  ADD RULES AFTER THIS LINE

csmbase.h: csmbase.c
	$(MCAN)/bin/$(HOST_ARCH)/hgen -h $@ $<
